name: flagdrive

services:
  flagdrive-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4859:4859"
    volumes:
      - database:/ctf/data

volumes:
  database: