name: flagdrive

services:
  flagdrive-checker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - flagdirve-mongo
    ports:
      - 14859:8000
    environment:
      - MONGO_ENABLED=1
      - MONGO_HOST=flagdirve-mongo
      - MONGO_PORT=27017
      - MONGO_USER=flagdrive-user
      - MONGO_PASSWORD=flagdrive-password
    mem_limit: 1G
    memswap_limit: 2G
    ulimits:
      core:
        soft: 0
        hard: 0
      nproc:
        soft: 4000
        hard: 4000
  flagdirve-mongo:
    image: mongo@sha256:8ecb514b00bdcc0bde67ef4e6c330385377a9dc68e24ee94e28c07c891647348
    restart: unless-stopped
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: flagdrive-user
      MONGO_INITDB_ROOT_PASSWORD: flagdrive-password
    mem_limit: 1G
    memswap_limit: 2G
    ulimits:
      core:
        soft: 0
        hard: 0
      nproc:
        soft: 4000
        hard: 4000

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1420
